name: Test

on:
    push:
        branches: "**"
    pull_request:
        branches: "**"

jobs:
    run-tests:
        name: Run tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Run tests
              run: npm run test:prod
